# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='webside',
            new_name='website',
        ),
    ]
